{% set name = "normaliz" %}
{% set version = "3.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Normaliz/Normaliz/releases/download/v{{ version }}/normaliz-{{ version }}.zip
  sha256: 3470e3f43313d8d840f9b6ea2940e3a01915c8dfbfd61766739cf4101cdae972
  patches:
    - 0001-Do-not-typedef-ssize_t.patch  # [win]
    - 0002-Fix-declarations-of-timeval.patch  # [win]
    - 0003-Do-not-use-TRUE-as-a-variable-name.patch  # [win]

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    # Normaliz has a history of breaking ABI changes in patch releases, so we
    # pin exactly, see
    # https://github.com/conda-forge/pynormaliz-feedstock/issues/10
    - {{ pin_subpackage("normaliz", max_pin="x.x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp            # [osx or win]
    - libgomp                # [linux]
    - autotools_clang_conda  # [win]
    - autoconf               # [not win]
    - automake               # [not win]
    - libtool                # [not win]
    - make                   # [not win]
  host:
    - gmp                    # [not win]
    - gmp                   # [win]
    - llvm-openmp            # [osx or win]
    - libeantic              # [not win]
    - libboost-headers       # [not win]
    - libflint               # [not win]
    - nauty
    - pthreads-win32         # [win]
  run:
    - llvm-openmp            # [osx or win]

test:
  commands:
    - test -f "$PREFIX/lib/libnormaliz.a"                       # [not win]
    - test -f "$PREFIX/lib/libnormaliz${SHLIB_EXT}"             # [not win]
    - test -f "$PREFIX/include/libnormaliz/matrix.h"            # [not win]
    - if not exist %LIBRARY_LIB%\\normaliz.lib exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\normaliz_static.lib exit 1    # [win]
    - if not exist %LIBRARY_INC%\\libnormaliz\\matrix.h exit 1  # [win]

about:
  home: https://www.normaliz.uni-osnabrueck.de
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: ' Normaliz is an open source tool for computations in affine monoids, vector configurations, lattice polytopes, and rational cones.'
  dev_url: https://github.com/Normaliz/Normaliz

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
