{% set name = "normaliz" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Normaliz/Normaliz/releases/download/v{{ version }}/normaliz-{{ version }}-full.zip
  sha256: 89d4551a8d527623768cea2e265200af35b896ab5e70352940769b7408bad3e1
  patches:
    - extern-kill.patch

build:
  number: 4
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("normaliz") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp          # [osx or win]
    - autotools_clang_conda  # [win]
    - autoconf             # [not win]
    - automake             # [not win]
    - libtool              # [not win]
    - make                 # [not win]
  host:
    - boost-cpp
    - gmp                  # [not win]
    - mpir                 # [win]
    - llvm-openmp          # [osx or win]
    - e-antic              # [not win]
    - libflint             # [not win]
    - arb                  # [not win]
    - nauty
    - pthreads-win32       # [win]
  run:
    - llvm-openmp          # [osx or win]

test:
  commands:
    - test -f "$PREFIX/lib/libnormaliz.a"                       # [not win]
    - test -f "$PREFIX/lib/libnormaliz${SHLIB_EXT}"             # [not win]
    - test -f "$PREFIX/include/libnormaliz/matrix.h"            # [not win]
    - if not exist %LIBRARY_LIB%\\normaliz.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\normaliz_static.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libnormaliz\\matrix.h exit 1   # [win]

about:
  home: https://www.normaliz.uni-osnabrueck.de
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: ' Normaliz is an open source tool for computations in affine monoids, vector configurations, lattice polytopes, and rational cones.'
  dev_url: https://github.com/Normaliz/Normaliz

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
